/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package leanface;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.2)", date = "2015-10-9")
public class LeanFaceService {

  public interface Iface {

    public int lean_face(String inputImgName, String ouputImgName) throws org.apache.thrift.TException;

  }

  public interface AsyncIface {

    public void lean_face(String inputImgName, String ouputImgName, org.apache.thrift.async.AsyncMethodCallback resultHandler) throws org.apache.thrift.TException;

  }

  public static class Client extends org.apache.thrift.TServiceClient implements Iface {
    public static class Factory implements org.apache.thrift.TServiceClientFactory<Client> {
      public Factory() {}
      public Client getClient(org.apache.thrift.protocol.TProtocol prot) {
        return new Client(prot);
      }
      public Client getClient(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TProtocol oprot) {
        return new Client(iprot, oprot);
      }
    }

    public Client(org.apache.thrift.protocol.TProtocol prot)
    {
      super(prot, prot);
    }

    public Client(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TProtocol oprot) {
      super(iprot, oprot);
    }

    public int lean_face(String inputImgName, String ouputImgName) throws org.apache.thrift.TException
    {
      send_lean_face(inputImgName, ouputImgName);
      return recv_lean_face();
    }

    public void send_lean_face(String inputImgName, String ouputImgName) throws org.apache.thrift.TException
    {
      lean_face_args args = new lean_face_args();
      args.setInputImgName(inputImgName);
      args.setOuputImgName(ouputImgName);
      sendBase("lean_face", args);
    }

    public int recv_lean_face() throws org.apache.thrift.TException
    {
      lean_face_result result = new lean_face_result();
      receiveBase(result, "lean_face");
      if (result.isSetSuccess()) {
        return result.success;
      }
      throw new org.apache.thrift.TApplicationException(org.apache.thrift.TApplicationException.MISSING_RESULT, "lean_face failed: unknown result");
    }

  }
  public static class AsyncClient extends org.apache.thrift.async.TAsyncClient implements AsyncIface {
    public static class Factory implements org.apache.thrift.async.TAsyncClientFactory<AsyncClient> {
      private org.apache.thrift.async.TAsyncClientManager clientManager;
      private org.apache.thrift.protocol.TProtocolFactory protocolFactory;
      public Factory(org.apache.thrift.async.TAsyncClientManager clientManager, org.apache.thrift.protocol.TProtocolFactory protocolFactory) {
        this.clientManager = clientManager;
        this.protocolFactory = protocolFactory;
      }
      public AsyncClient getAsyncClient(org.apache.thrift.transport.TNonblockingTransport transport) {
        return new AsyncClient(protocolFactory, clientManager, transport);
      }
    }

    public AsyncClient(org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.async.TAsyncClientManager clientManager, org.apache.thrift.transport.TNonblockingTransport transport) {
      super(protocolFactory, clientManager, transport);
    }

    public void lean_face(String inputImgName, String ouputImgName, org.apache.thrift.async.AsyncMethodCallback resultHandler) throws org.apache.thrift.TException {
      checkReady();
      lean_face_call method_call = new lean_face_call(inputImgName, ouputImgName, resultHandler, this, ___protocolFactory, ___transport);
      this.___currentMethod = method_call;
      ___manager.call(method_call);
    }

    public static class lean_face_call extends org.apache.thrift.async.TAsyncMethodCall {
      private String inputImgName;
      private String ouputImgName;
      public lean_face_call(String inputImgName, String ouputImgName, org.apache.thrift.async.AsyncMethodCallback resultHandler, org.apache.thrift.async.TAsyncClient client, org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.transport.TNonblockingTransport transport) throws org.apache.thrift.TException {
        super(client, protocolFactory, transport, resultHandler, false);
        this.inputImgName = inputImgName;
        this.ouputImgName = ouputImgName;
      }

      public void write_args(org.apache.thrift.protocol.TProtocol prot) throws org.apache.thrift.TException {
        prot.writeMessageBegin(new org.apache.thrift.protocol.TMessage("lean_face", org.apache.thrift.protocol.TMessageType.CALL, 0));
        lean_face_args args = new lean_face_args();
        args.setInputImgName(inputImgName);
        args.setOuputImgName(ouputImgName);
        args.write(prot);
        prot.writeMessageEnd();
      }

      public int getResult() throws org.apache.thrift.TException {
        if (getState() != org.apache.thrift.async.TAsyncMethodCall.State.RESPONSE_READ) {
          throw new IllegalStateException("Method call not finished!");
        }
        org.apache.thrift.transport.TMemoryInputTransport memoryTransport = new org.apache.thrift.transport.TMemoryInputTransport(getFrameBuffer().array());
        org.apache.thrift.protocol.TProtocol prot = client.getProtocolFactory().getProtocol(memoryTransport);
        return (new Client(prot)).recv_lean_face();
      }
    }

  }

  public static class Processor<I extends Iface> extends org.apache.thrift.TBaseProcessor<I> implements org.apache.thrift.TProcessor {
    private static final Logger LOGGER = LoggerFactory.getLogger(Processor.class.getName());
    public Processor(I iface) {
      super(iface, getProcessMap(new HashMap<String, org.apache.thrift.ProcessFunction<I, ? extends org.apache.thrift.TBase>>()));
    }

    protected Processor(I iface, Map<String,  org.apache.thrift.ProcessFunction<I, ? extends  org.apache.thrift.TBase>> processMap) {
      super(iface, getProcessMap(processMap));
    }

    private static <I extends Iface> Map<String,  org.apache.thrift.ProcessFunction<I, ? extends  org.apache.thrift.TBase>> getProcessMap(Map<String,  org.apache.thrift.ProcessFunction<I, ? extends  org.apache.thrift.TBase>> processMap) {
      processMap.put("lean_face", new lean_face());
      return processMap;
    }

    public static class lean_face<I extends Iface> extends org.apache.thrift.ProcessFunction<I, lean_face_args> {
      public lean_face() {
        super("lean_face");
      }

      public lean_face_args getEmptyArgsInstance() {
        return new lean_face_args();
      }

      protected boolean isOneway() {
        return false;
      }

      public lean_face_result getResult(I iface, lean_face_args args) throws org.apache.thrift.TException {
        lean_face_result result = new lean_face_result();
        result.success = iface.lean_face(args.inputImgName, args.ouputImgName);
        result.setSuccessIsSet(true);
        return result;
      }
    }

  }

  public static class AsyncProcessor<I extends AsyncIface> extends org.apache.thrift.TBaseAsyncProcessor<I> {
    private static final Logger LOGGER = LoggerFactory.getLogger(AsyncProcessor.class.getName());
    public AsyncProcessor(I iface) {
      super(iface, getProcessMap(new HashMap<String, org.apache.thrift.AsyncProcessFunction<I, ? extends org.apache.thrift.TBase, ?>>()));
    }

    protected AsyncProcessor(I iface, Map<String,  org.apache.thrift.AsyncProcessFunction<I, ? extends  org.apache.thrift.TBase, ?>> processMap) {
      super(iface, getProcessMap(processMap));
    }

    private static <I extends AsyncIface> Map<String,  org.apache.thrift.AsyncProcessFunction<I, ? extends  org.apache.thrift.TBase,?>> getProcessMap(Map<String,  org.apache.thrift.AsyncProcessFunction<I, ? extends  org.apache.thrift.TBase, ?>> processMap) {
      processMap.put("lean_face", new lean_face());
      return processMap;
    }

    public static class lean_face<I extends AsyncIface> extends org.apache.thrift.AsyncProcessFunction<I, lean_face_args, Integer> {
      public lean_face() {
        super("lean_face");
      }

      public lean_face_args getEmptyArgsInstance() {
        return new lean_face_args();
      }

      public AsyncMethodCallback<Integer> getResultHandler(final AsyncFrameBuffer fb, final int seqid) {
        final org.apache.thrift.AsyncProcessFunction fcall = this;
        return new AsyncMethodCallback<Integer>() { 
          public void onComplete(Integer o) {
            lean_face_result result = new lean_face_result();
            result.success = o;
            result.setSuccessIsSet(true);
            try {
              fcall.sendResponse(fb,result, org.apache.thrift.protocol.TMessageType.REPLY,seqid);
              return;
            } catch (Exception e) {
              LOGGER.error("Exception writing to internal frame buffer", e);
            }
            fb.close();
          }
          public void onError(Exception e) {
            byte msgType = org.apache.thrift.protocol.TMessageType.REPLY;
            org.apache.thrift.TBase msg;
            lean_face_result result = new lean_face_result();
            {
              msgType = org.apache.thrift.protocol.TMessageType.EXCEPTION;
              msg = (org.apache.thrift.TBase)new org.apache.thrift.TApplicationException(org.apache.thrift.TApplicationException.INTERNAL_ERROR, e.getMessage());
            }
            try {
              fcall.sendResponse(fb,msg,msgType,seqid);
              return;
            } catch (Exception ex) {
              LOGGER.error("Exception writing to internal frame buffer", ex);
            }
            fb.close();
          }
        };
      }

      protected boolean isOneway() {
        return false;
      }

      public void start(I iface, lean_face_args args, org.apache.thrift.async.AsyncMethodCallback<Integer> resultHandler) throws TException {
        iface.lean_face(args.inputImgName, args.ouputImgName,resultHandler);
      }
    }

  }

  public static class lean_face_args implements org.apache.thrift.TBase<lean_face_args, lean_face_args._Fields>, java.io.Serializable, Cloneable, Comparable<lean_face_args>   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("lean_face_args");

    private static final org.apache.thrift.protocol.TField INPUT_IMG_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("inputImgName", org.apache.thrift.protocol.TType.STRING, (short)1);
    private static final org.apache.thrift.protocol.TField OUPUT_IMG_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("ouputImgName", org.apache.thrift.protocol.TType.STRING, (short)2);

    private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
    static {
      schemes.put(StandardScheme.class, new lean_face_argsStandardSchemeFactory());
      schemes.put(TupleScheme.class, new lean_face_argsTupleSchemeFactory());
    }

    public String inputImgName; // required
    public String ouputImgName; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      INPUT_IMG_NAME((short)1, "inputImgName"),
      OUPUT_IMG_NAME((short)2, "ouputImgName");

      private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

      static {
        for (_Fields field : EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 1: // INPUT_IMG_NAME
            return INPUT_IMG_NAME;
          case 2: // OUPUT_IMG_NAME
            return OUPUT_IMG_NAME;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      public static _Fields findByName(String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final String _fieldName;

      _Fields(short thriftId, String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.INPUT_IMG_NAME, new org.apache.thrift.meta_data.FieldMetaData("inputImgName", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
      tmpMap.put(_Fields.OUPUT_IMG_NAME, new org.apache.thrift.meta_data.FieldMetaData("ouputImgName", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
      metaDataMap = Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(lean_face_args.class, metaDataMap);
    }

    public lean_face_args() {
    }

    public lean_face_args(
      String inputImgName,
      String ouputImgName)
    {
      this();
      this.inputImgName = inputImgName;
      this.ouputImgName = ouputImgName;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public lean_face_args(lean_face_args other) {
      if (other.isSetInputImgName()) {
        this.inputImgName = other.inputImgName;
      }
      if (other.isSetOuputImgName()) {
        this.ouputImgName = other.ouputImgName;
      }
    }

    public lean_face_args deepCopy() {
      return new lean_face_args(this);
    }

    @Override
    public void clear() {
      this.inputImgName = null;
      this.ouputImgName = null;
    }

    public String getInputImgName() {
      return this.inputImgName;
    }

    public lean_face_args setInputImgName(String inputImgName) {
      this.inputImgName = inputImgName;
      return this;
    }

    public void unsetInputImgName() {
      this.inputImgName = null;
    }

    /** Returns true if field inputImgName is set (has been assigned a value) and false otherwise */
    public boolean isSetInputImgName() {
      return this.inputImgName != null;
    }

    public void setInputImgNameIsSet(boolean value) {
      if (!value) {
        this.inputImgName = null;
      }
    }

    public String getOuputImgName() {
      return this.ouputImgName;
    }

    public lean_face_args setOuputImgName(String ouputImgName) {
      this.ouputImgName = ouputImgName;
      return this;
    }

    public void unsetOuputImgName() {
      this.ouputImgName = null;
    }

    /** Returns true if field ouputImgName is set (has been assigned a value) and false otherwise */
    public boolean isSetOuputImgName() {
      return this.ouputImgName != null;
    }

    public void setOuputImgNameIsSet(boolean value) {
      if (!value) {
        this.ouputImgName = null;
      }
    }

    public void setFieldValue(_Fields field, Object value) {
      switch (field) {
      case INPUT_IMG_NAME:
        if (value == null) {
          unsetInputImgName();
        } else {
          setInputImgName((String)value);
        }
        break;

      case OUPUT_IMG_NAME:
        if (value == null) {
          unsetOuputImgName();
        } else {
          setOuputImgName((String)value);
        }
        break;

      }
    }

    public Object getFieldValue(_Fields field) {
      switch (field) {
      case INPUT_IMG_NAME:
        return getInputImgName();

      case OUPUT_IMG_NAME:
        return getOuputImgName();

      }
      throw new IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new IllegalArgumentException();
      }

      switch (field) {
      case INPUT_IMG_NAME:
        return isSetInputImgName();
      case OUPUT_IMG_NAME:
        return isSetOuputImgName();
      }
      throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that) {
      if (that == null)
        return false;
      if (that instanceof lean_face_args)
        return this.equals((lean_face_args)that);
      return false;
    }

    public boolean equals(lean_face_args that) {
      if (that == null)
        return false;

      boolean this_present_inputImgName = true && this.isSetInputImgName();
      boolean that_present_inputImgName = true && that.isSetInputImgName();
      if (this_present_inputImgName || that_present_inputImgName) {
        if (!(this_present_inputImgName && that_present_inputImgName))
          return false;
        if (!this.inputImgName.equals(that.inputImgName))
          return false;
      }

      boolean this_present_ouputImgName = true && this.isSetOuputImgName();
      boolean that_present_ouputImgName = true && that.isSetOuputImgName();
      if (this_present_ouputImgName || that_present_ouputImgName) {
        if (!(this_present_ouputImgName && that_present_ouputImgName))
          return false;
        if (!this.ouputImgName.equals(that.ouputImgName))
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      List<Object> list = new ArrayList<Object>();

      boolean present_inputImgName = true && (isSetInputImgName());
      list.add(present_inputImgName);
      if (present_inputImgName)
        list.add(inputImgName);

      boolean present_ouputImgName = true && (isSetOuputImgName());
      list.add(present_ouputImgName);
      if (present_ouputImgName)
        list.add(ouputImgName);

      return list.hashCode();
    }

    @Override
    public int compareTo(lean_face_args other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;

      lastComparison = Boolean.valueOf(isSetInputImgName()).compareTo(other.isSetInputImgName());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetInputImgName()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.inputImgName, other.inputImgName);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      lastComparison = Boolean.valueOf(isSetOuputImgName()).compareTo(other.isSetOuputImgName());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetOuputImgName()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.ouputImgName, other.ouputImgName);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
      schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
      schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
    }

    @Override
    public String toString() {
      StringBuilder sb = new StringBuilder("lean_face_args(");
      boolean first = true;

      sb.append("inputImgName:");
      if (this.inputImgName == null) {
        sb.append("null");
      } else {
        sb.append(this.inputImgName);
      }
      first = false;
      if (!first) sb.append(", ");
      sb.append("ouputImgName:");
      if (this.ouputImgName == null) {
        sb.append("null");
      } else {
        sb.append(this.ouputImgName);
      }
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
      // check for required fields
      // check for sub-struct validity
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
      try {
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class lean_face_argsStandardSchemeFactory implements SchemeFactory {
      public lean_face_argsStandardScheme getScheme() {
        return new lean_face_argsStandardScheme();
      }
    }

    private static class lean_face_argsStandardScheme extends StandardScheme<lean_face_args> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, lean_face_args struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            case 1: // INPUT_IMG_NAME
              if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
                struct.inputImgName = iprot.readString();
                struct.setInputImgNameIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            case 2: // OUPUT_IMG_NAME
              if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
                struct.ouputImgName = iprot.readString();
                struct.setOuputImgNameIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, lean_face_args struct) throws org.apache.thrift.TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        if (struct.inputImgName != null) {
          oprot.writeFieldBegin(INPUT_IMG_NAME_FIELD_DESC);
          oprot.writeString(struct.inputImgName);
          oprot.writeFieldEnd();
        }
        if (struct.ouputImgName != null) {
          oprot.writeFieldBegin(OUPUT_IMG_NAME_FIELD_DESC);
          oprot.writeString(struct.ouputImgName);
          oprot.writeFieldEnd();
        }
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class lean_face_argsTupleSchemeFactory implements SchemeFactory {
      public lean_face_argsTupleScheme getScheme() {
        return new lean_face_argsTupleScheme();
      }
    }

    private static class lean_face_argsTupleScheme extends TupleScheme<lean_face_args> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, lean_face_args struct) throws org.apache.thrift.TException {
        TTupleProtocol oprot = (TTupleProtocol) prot;
        BitSet optionals = new BitSet();
        if (struct.isSetInputImgName()) {
          optionals.set(0);
        }
        if (struct.isSetOuputImgName()) {
          optionals.set(1);
        }
        oprot.writeBitSet(optionals, 2);
        if (struct.isSetInputImgName()) {
          oprot.writeString(struct.inputImgName);
        }
        if (struct.isSetOuputImgName()) {
          oprot.writeString(struct.ouputImgName);
        }
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, lean_face_args struct) throws org.apache.thrift.TException {
        TTupleProtocol iprot = (TTupleProtocol) prot;
        BitSet incoming = iprot.readBitSet(2);
        if (incoming.get(0)) {
          struct.inputImgName = iprot.readString();
          struct.setInputImgNameIsSet(true);
        }
        if (incoming.get(1)) {
          struct.ouputImgName = iprot.readString();
          struct.setOuputImgNameIsSet(true);
        }
      }
    }

  }

  public static class lean_face_result implements org.apache.thrift.TBase<lean_face_result, lean_face_result._Fields>, java.io.Serializable, Cloneable, Comparable<lean_face_result>   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("lean_face_result");

    private static final org.apache.thrift.protocol.TField SUCCESS_FIELD_DESC = new org.apache.thrift.protocol.TField("success", org.apache.thrift.protocol.TType.I32, (short)0);

    private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
    static {
      schemes.put(StandardScheme.class, new lean_face_resultStandardSchemeFactory());
      schemes.put(TupleScheme.class, new lean_face_resultTupleSchemeFactory());
    }

    public int success; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      SUCCESS((short)0, "success");

      private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

      static {
        for (_Fields field : EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 0: // SUCCESS
            return SUCCESS;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      public static _Fields findByName(String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final String _fieldName;

      _Fields(short thriftId, String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    private static final int __SUCCESS_ISSET_ID = 0;
    private byte __isset_bitfield = 0;
    public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.SUCCESS, new org.apache.thrift.meta_data.FieldMetaData("success", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
      metaDataMap = Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(lean_face_result.class, metaDataMap);
    }

    public lean_face_result() {
    }

    public lean_face_result(
      int success)
    {
      this();
      this.success = success;
      setSuccessIsSet(true);
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public lean_face_result(lean_face_result other) {
      __isset_bitfield = other.__isset_bitfield;
      this.success = other.success;
    }

    public lean_face_result deepCopy() {
      return new lean_face_result(this);
    }

    @Override
    public void clear() {
      setSuccessIsSet(false);
      this.success = 0;
    }

    public int getSuccess() {
      return this.success;
    }

    public lean_face_result setSuccess(int success) {
      this.success = success;
      setSuccessIsSet(true);
      return this;
    }

    public void unsetSuccess() {
      __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __SUCCESS_ISSET_ID);
    }

    /** Returns true if field success is set (has been assigned a value) and false otherwise */
    public boolean isSetSuccess() {
      return EncodingUtils.testBit(__isset_bitfield, __SUCCESS_ISSET_ID);
    }

    public void setSuccessIsSet(boolean value) {
      __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __SUCCESS_ISSET_ID, value);
    }

    public void setFieldValue(_Fields field, Object value) {
      switch (field) {
      case SUCCESS:
        if (value == null) {
          unsetSuccess();
        } else {
          setSuccess((Integer)value);
        }
        break;

      }
    }

    public Object getFieldValue(_Fields field) {
      switch (field) {
      case SUCCESS:
        return Integer.valueOf(getSuccess());

      }
      throw new IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new IllegalArgumentException();
      }

      switch (field) {
      case SUCCESS:
        return isSetSuccess();
      }
      throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that) {
      if (that == null)
        return false;
      if (that instanceof lean_face_result)
        return this.equals((lean_face_result)that);
      return false;
    }

    public boolean equals(lean_face_result that) {
      if (that == null)
        return false;

      boolean this_present_success = true;
      boolean that_present_success = true;
      if (this_present_success || that_present_success) {
        if (!(this_present_success && that_present_success))
          return false;
        if (this.success != that.success)
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      List<Object> list = new ArrayList<Object>();

      boolean present_success = true;
      list.add(present_success);
      if (present_success)
        list.add(success);

      return list.hashCode();
    }

    @Override
    public int compareTo(lean_face_result other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;

      lastComparison = Boolean.valueOf(isSetSuccess()).compareTo(other.isSetSuccess());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetSuccess()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.success, other.success);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
      schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
      schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
      }

    @Override
    public String toString() {
      StringBuilder sb = new StringBuilder("lean_face_result(");
      boolean first = true;

      sb.append("success:");
      sb.append(this.success);
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
      // check for required fields
      // check for sub-struct validity
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
      try {
        // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
        __isset_bitfield = 0;
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class lean_face_resultStandardSchemeFactory implements SchemeFactory {
      public lean_face_resultStandardScheme getScheme() {
        return new lean_face_resultStandardScheme();
      }
    }

    private static class lean_face_resultStandardScheme extends StandardScheme<lean_face_result> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, lean_face_result struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            case 0: // SUCCESS
              if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
                struct.success = iprot.readI32();
                struct.setSuccessIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, lean_face_result struct) throws org.apache.thrift.TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        if (struct.isSetSuccess()) {
          oprot.writeFieldBegin(SUCCESS_FIELD_DESC);
          oprot.writeI32(struct.success);
          oprot.writeFieldEnd();
        }
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class lean_face_resultTupleSchemeFactory implements SchemeFactory {
      public lean_face_resultTupleScheme getScheme() {
        return new lean_face_resultTupleScheme();
      }
    }

    private static class lean_face_resultTupleScheme extends TupleScheme<lean_face_result> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, lean_face_result struct) throws org.apache.thrift.TException {
        TTupleProtocol oprot = (TTupleProtocol) prot;
        BitSet optionals = new BitSet();
        if (struct.isSetSuccess()) {
          optionals.set(0);
        }
        oprot.writeBitSet(optionals, 1);
        if (struct.isSetSuccess()) {
          oprot.writeI32(struct.success);
        }
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, lean_face_result struct) throws org.apache.thrift.TException {
        TTupleProtocol iprot = (TTupleProtocol) prot;
        BitSet incoming = iprot.readBitSet(1);
        if (incoming.get(0)) {
          struct.success = iprot.readI32();
          struct.setSuccessIsSet(true);
        }
      }
    }

  }

}
