/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "LeanFace_constants.h"

namespace leanface {

const LeanFaceConstants g_LeanFace_constants;

LeanFaceConstants::LeanFaceConstants() {
}

} // namespace

