/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef LeanFace_CONSTANTS_H
#define LeanFace_CONSTANTS_H

#include "LeanFace_types.h"

namespace leanface {

class LeanFaceConstants {
 public:
  LeanFaceConstants();

};

extern const LeanFaceConstants g_LeanFace_constants;

} // namespace

#endif
